name: Build and Publish Sheets

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r sheets/requirements.txt

      - name: Generate spreadsheet
        working-directory: ./sheets
        run: python generate_scrcmd_spreadsheet.py

      - name: Upload to Google Sheets
        working-directory: ./sheets
        run: python upload_to_sheets.py
